language: node_js
node_js:
- node
sudo: required
dist: trusty
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
  before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - "./build.sh"
